spring.application.name=web-head-ai

gemini.api.url=${GEMINI_API_URL}
gemini.api.key=${GEMINI_API_KEY}
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
spring.mongodb.uri=${MONGODB_URI}
google.client.id=${GOOGLE_CLIENT_ID}